Cargo.toml
README.md
src/backend/openssl.rs
src/imp/openssl.rs
src/imp/schannel.rs
src/imp/security_framework.rs
src/lib.rs
src/test.rs

Use high level OpenSSL wrappers for configuration logic as well.
cc @alexcrichton Not totally sold on the naming here, but I can't really think of anything better.

Restructure API

---

Cargo.toml
src/backend/openssl.rs
src/backend/schannel.rs
src/backend/security_framework.rs
src/imp/openssl.rs
src/imp/schannel.rs
src/imp/security_framework.rs

This commit updates the various backends to export some more information, where
all of these changes were motivated in getting the tokio-tls test suite running
again. (it's just a bunch of smoke tests really). A summary of the changes are:
* Add an `ErrorExt` trait to each backend to lower a `native_tls::Error` to the
backend-specific error. This allows inspection of errors codes and such if
necessary.
* Add `TlsConnectorBuilderExt` to the `security_framework` backend, with one
function called `anchor_certificates`. This function transitively calls the
security framework crate's `anchor_certificates` function to set a custom
trusted certificate for a connection. Along the way this required using the
`ClientBuilder` type which in turn required changes to work with async I/O.
The changes to …

Expose a few more details of underlying backends

---

src/imp/openssl.rs
src/imp/schannel.rs
src/imp/security_framework.rs
src/lib.rs

Building a TlsAcceptor or TlsConnector can be non trivial, so cloning allows easy reuse without having to rebuild from scratch.

Make acceptors and connectors cloneable

---

Cargo.toml
src/imp/schannel.rs
src/test.rs

adds a trait in the connectorBuilder that allows users to specify a
verification callback to use in the event that a new connection's
validation fails

specify verification callbacks for schannel

---

src/lib.rs

This allows making a `native_tls::Error` from e.g. a `openssl::error::ErrorStack`. Previously you'd have to do `.into().into()`, but type inference wasn't smart enough to figure this out.
Note this works because of the blanket `impl Into<T> for T`.

Enable conversion from internal errors to Error

---

Cargo.toml

This PR is similar to https://github.com/sfackler/rust-native-tls/pull/68 but only updates the `lazy_static` dep to avoid breaking the build.
Tests passing on Windows and Ubuntu.

Update lazy_static to 1.0

---

Cargo.toml
src/imp/openssl.rs
src/lib.rs

Adding cert on android print error instead of crash
Now when load_android_root_certs failed, it'll print error instead of return error.
ErrorStack([Error { code: 185057381, library: "x509 certificate routines", function: "X509_STORE_add_cert", reason: "cert already in hash table", file: "crypto/x509/x509_lu.c", line: 326 }])
Without, I don't know how can I use hyper_tls on android with certs duplicated

Android add certs error: already in hash table

---

Cargo.toml
src/imp/openssl.rs

The stack is the reverse of what you might expect due to the way
PKCS12_parse is implemented, so we need to load it backwards.
Closes #110

Reverse chain loading for openssl

---

.circleci/config.yml
Cargo.toml
appveyor.yml
src/imp/openssl.rs
src/imp/schannel.rs
src/imp/security_framework.rs
src/lib.rs

It should not be necessary to have `S: Read + Write` to get at references to `S` through `TlsStream<S>`, so this patch removes those bounds. This matters little in practice, since you likely can't construct a `TlsStream` on an `S` that isn't `Read + Write`, but it does mean that downstream crates that wrap `TlsStream` do not have to repeat the `Read + Write` bounds for _their_ `get_` methods.

Relax bounds for get_ref and get_mut

---

Cargo.toml
src/imp/openssl.rs
src/imp/schannel.rs
src/imp/security_framework.rs
src/lib.rs
src/test.rs

Implements a way to distrust the system cert store on all backends.
- On macOS, this just uses `trust_anchor_certificates_only`.
- On Windows, this uses a custom `verify_callback` that manually checks that the root cert exists in the user-specified root certs.
- On OpenSSL, this manually creates a new `X509Store` with the user-specified root certs and sets it with `set_verify_cert_store`. This is the one I'm least sure about -- it is probably more correct to avoid calling `set_default_verify_paths`, but that currently happens on builder construction, and moving where that happens might be a breaking change (as `set_default_verify_paths` reads environment variables, which are set process-wide).
Closes #41.

Implement bindings to only use supplied root certificates for validating the server

---

src/imp/openssl.rs

It's possible use `flatten` instead `flat_map` from rust 1.29 -- https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.flatten

Fix clippy warnings

---

src/imp/openssl.rs
src/imp/schannel.rs
src/imp/security_framework.rs
src/lib.rs

Closes #99
Derived for Windows and macOS, hand-rolled for Linux due to a missing downstream Debug dependency. I whipped up a little test script and ran it across Linux, macOS, and Windows and to my eyes it doesn't appear to be leaking anything sensitive.
---
```rust
extern crate native_tls;
use native_tls::{Identity, TlsConnector};
use std::fs::File;
use std::io::Read;
use std::path::Path;
fn main() {
let pkcs12 = File::open(
Path::new(env!("CARGO_MANIFEST_DIR"))
.join("test")
.join("identity.p12"),
)
.map(|mut f| {
let mut pkcs12 = vec![];
f.read_to_end(&mut pkcs12).unwrap();
pkcs12
})
.unwrap();
let tls = TlsConnector::builder()
.identity(Identity::from_pkcs12(&pkcs12, "mypass").unwrap())
.build()
.unwrap();
println!("{:#?}", tls);
}
```
<details><summary>Linux</summary>
```rust …
```

Implements Debug for `TlsConnector`

---

Cargo.toml
src/imp/security_framework.rs

Updating dependencies to their latest version. The reason is that [grcov](https://github.com/mozilla/grcov) is failing to collect coverage during the build/test due to a bug in https://github.com/servo/core-foundation-rs/pull/357 that is dependency of `security-framework`
@sfackler can you have a look and merge?
Thanks

update to latest dependecies version

---

.circleci/config.yml
Cargo.toml
src/imp/openssl.rs
src/imp/schannel.rs
src/imp/security_framework.rs
src/lib.rs
src/test.rs

An alternative to #157 .
Slightly more surgical in a lot of places, doesn't require an extra feature, correct error handling on macOS, and some simple tests.
Closes #49.

Implement ALPN support

---

.github/workflows/ci.yml
src/imp/schannel.rs
src/test.rs

`max_protocol_version` set a maximum of one version earlier than it was supposed to.
There are two tests that exercise this. I believe they didn't catch it because:
- `server_tls11_only` sets the same `min_protocol_version` and `max_protocol_version`, which causes `schannel` to be configured with no versions at all, which flips it into its default setting (?) which the test also accepts.
- `server_no_shared_protocol` was supposed to fail and still fails if you make it even more restrictive.

Fix off-by-one error in schannel's max_protocol_version

---

Cargo.toml
src/imp/security_framework.rs
src/lib.rs

This replaces [`lazy_static`](https://crates.io/crates/lazy_static) with [`once_cell`](https://crates.io/crates/once_cell). Couple of reasons:
- The ecosystem in general is shifting away from `lazy_static` to `once_cell`, so hopefully one day we can eliminate `lazy_static` from the dependency tree.
- `lazy_static` is unmaintained.
- `once_cell` is much closer to whats going to be [stabilized in Rust v1.70](https://github.com/rust-lang/rust/pull/105587) and [future](https://github.com/rust-lang/rust/issues/109736) [versions](https://github.com/rust-lang/rust/issues/109737): https://github.com/rust-lang/rust/issues/74465.

Replace `lazy_static` with `once_cell`

---

src/lib.rs

Fixes #266 
Update the Builders documentation to make clearer how to construct them

Update builders documentation

---

Cargo.toml
src/imp/security_framework.rs

When using the changes in #294, I found that there was an issue with errno (https://github.com/lambda-fairy/rust-errno/pull/95) linking to the correct errno calls for visionOS.
Given that [`Identity::from_pkcs8` is unimplemented for non-macos targets](https://github.com/sfackler/rust-native-tls/blob/0b69ce6a3c4bfe973ede44f6862fc13f3f09c773/src/imp/security_framework.rs#L84-L88) I figured it'd be best to just remove `tempfile` as a dependency for those targets.

Make tempfile be a macos-only dependency

---

Cargo.toml
src/imp/security_framework.rs
src/lib.rs

Apple Vision Pro support was added as a tier 3 target to rust in https://github.com/rust-lang/rust/pull/121419 with `target_os` of `visionos`.
Depends on:

Added visionos target support

---

Cargo.toml
src/imp/openssl.rs
src/lib.rs

Stop using deprecated openssl-probe APIs
